# Generated by Django 6.0.7 on 2026-07-30 21:08

import apps.contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage')], max_length=10)),
                ('position', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Vide pour un CDI', null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Grille salariale: 2 000 000 à 15 000 000 GNF', max_digits=14)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré'), ('TERMINATED', 'Résilié'), ('RENEWED', 'Renouvelé')], default='ACTIVE', max_length=15)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.contracts.models.contract_file_path)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
