# Generated by Django 6.0.7 on 2026-07-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('ASSET', 'Actif'), ('LIABILITY', 'Passif'), ('EXPENSE', 'Charge'), ('REVENUE', 'Produit'), ('EQUITY', 'Capitaux propres')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(default='NSIA Banque Guinée', max_length=150)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('currency', models.CharField(choices=[('GNF', 'GNF'), ('USD', 'USD')], default='GNF', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(help_text='Poste de dépense: carburant, maintenance, salaires...', max_length=150)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('TRUCK', 'Camion'), ('EQUIPMENT', 'Équipement'), ('VEHICLE', 'Véhicule léger'), ('OTHER', 'Autre')], max_length=15)),
                ('registration_number', models.CharField(blank=True, help_text='Immatriculation, pour les camions', max_length=50)),
                ('acquisition_date', models.DateField()),
                ('acquisition_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('useful_life_months', models.PositiveIntegerField(help_text="Durée d'amortissement en mois")),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('tonnage', models.DecimalField(blank=True, decimal_places=2, help_text='Tonnes de minerai transportées', max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(choices=[('GNF', 'GNF'), ('USD', 'USD')], default='USD', max_length=3)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('UNPAID', 'Non payée'), ('PARTIALLY_PAID', 'Partiellement payée'), ('PAID', 'Payée'), ('OVERDUE', 'En retard')], default='UNPAID', max_length=15)),
                ('last_reminder_sent', models.DateField(blank=True, help_text='Gestion des relances automatiques', null=True)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('label', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('currency', models.CharField(choices=[('GNF', 'GNF'), ('USD', 'USD')], default='GNF', max_length=3)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('reconciled', models.BooleanField(default=False, help_text='Rapprochement bancaire')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(choices=[('GNF', 'GNF'), ('USD', 'USD')], default='GNF', max_length=3)),
                ('status', models.CharField(choices=[('ISSUED', 'Émis'), ('DELIVERED', 'Livré'), ('INVOICED', 'Facturé'), ('PAID', 'Payé'), ('CANCELLED', 'Annulé')], default='ISSUED', max_length=10)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('FUEL', 'Carburant'), ('TIRES', 'Pneus'), ('MAINTENANCE', 'Maintenance'), ('PPE', 'EPI'), ('OTHER', 'Autre')], max_length=15)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Évaluation /5', max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('expected_inflow', models.DecimalField(decimal_places=2, default=0, help_text='Encaissements attendus (revenus transport)', max_digits=18)),
                ('expected_outflow', models.DecimalField(decimal_places=2, default=0, help_text='Décaissements attendus (salaires, fournisseurs, charges)', max_digits=18)),
                ('actual_inflow', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('actual_outflow', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
    ]
