# Generated by Django 6.0.7 on 2026-07-30 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.department'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounting.purchaserequest'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounting.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='treasuryforecast',
            unique_together={('month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('department', 'category', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date', 'account'], name='accounting__date_276557_idx'),
        ),
    ]
