# Generated by Django 6.0.7 on 2026-07-30 21:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Validé'), ('PAID', 'Payé')], default='DRAFT', max_length=10)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=Decimal('1.25'), help_text='Majoration heures sup (ex: 1.25 = +25%)', max_digits=6)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, help_text='Avances sur salaire', max_digits=14)),
                ('cnss_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payslips/')),
            ],
            options={
                'ordering': ['-payroll_run__period_year', '-payroll_run__period_month'],
            },
        ),
        migrations.CreateModel(
            name='SalaryGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=150, unique=True)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('GNF', 'GNF'), ('USD', 'USD')], default='GNF', max_length=3)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
