# Generated by Django 6.0.7 on 2026-07-30 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('organizations', '0002_initial'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payroll_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun'),
        ),
        migrations.AddField(
            model_name='salarygrid',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_grids', to='organizations.department'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together={('period_month', 'period_year')},
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('payroll_run', 'employee')},
        ),
    ]
